### PR TITLE
1.0.5

### PR DESCRIPTION
**Pull request by 0x16c3**
This pull request adds;
- List get queries
- Staff get queries
- Staff search queries
- User search queries
- `alternative` attribute to the Name object
- Message activities
- Support for users, favourites, staff, statistics, rankings, and studios
- Support for user list and text activities
- `is_adult` to both anime and manga objects
- User object to text activities
- Profile colors and other fields to the user object
- Timestamps to the date object

and;
- Fixes typos & bugs
- Tidies up and organizes required fields in every object

### CODE REVIEW

**Comment by 0x16c3** [comment]
This pull request sadly also removes the new average score search.
But that issue might be solved by creating a system for additional search parameters in the future.

**Comment by AndrielFR** [comment]
Can I merge now?

**Comment by 0x16c3** [comment]
> Can I merge now?

Yep, all good!

**Comment by AndrielFR** [comment]
> > Can I merge now?
> 
> Yep, all good!

Ok, thank you.

**Pull request merged**
