### PR TITLE
Large refactoring to simplify code and remove duplicate code

### PR DESCRIPTION
**Pull request by r-hensley**
Hello, thank you for your wonderful library. It's very well made and works well. I've written in the changelog file but I'll write it again here. 

I spent some time just consolidating a lot of duplicated code:

- Every class was defined with duplicate definitions of `raw()`, `__repr__()`, and `__str__()`, so I moved all those to a base class called `Object` and had the anilist classes derive from that. Additionally, if a class has an ID, I made a `Hashable` type as a subclass of `Object` which implemented `__eq__()` and `__hash__()`. 
- The logic for API calls in every class was duplicated, so I moved it all to one function, `api_query()` and had all functions call that instead.
- The data analysis and packaging of the information received from the response was mostly duplicated between the `sync_client.py` file and the `async_client.py` for the purpose of having different logic in the api query step, but I moved all the steps that were the same for both files out into a third external file `client_process.py` so they can be called equally.

--------------------

One change I made that technically could be breaking is I removed the mass ignoring of exceptions in the data packaging code. There were many instances of code like:
```py
try:
    # code here
except Exception:
    pass
```
This probably isn't good because it hides errors which can lead to both complications in debugging and unintended behavior in production. For now, I left the structure of the code the same and just changed "pass" to "raise". To undo this change, one can do a substitution operation in `client_process.py` to replace "raise" back to "pass".

------------------

Finally, I fixed what I believe to be an error but I'm technically not sure. In the function `get_message_activity()` 

https://github.com/AmanoTeam/python-anilist/blob/a21b26b1baf6e134eeac8b9251346a9bcbef2d19/anilist/sync_client.py#L1271

it looks like there are two functions inside the one definition, and the function starts over with a new query call here: 
https://github.com/AmanoTeam/python-anilist/blob/a21b26b1baf6e134eeac8b9251346a9bcbef2d19/anilist/sync_client.py#L1322

so I split the function into `get_message_activity()` and `get_message_activity_sent()`.

https://github.com/r-hensley/python-anilist/blob/f9183a0656d5db8a9da68902f36dc67c355201ab/anilist/sync_client.py#L376-390

--------------------

I ran all the tests and (after changing one obsolete ID in one of the tests), confirmed they all passed:
```py
C:\Users\ryry0\AppData\Local\Programs\Python\Python310\python.exe "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pycharm\_jb_pytest_runner.py" --path C:/Users/ryry0/Documents/Python/anime_staff_checker/pythonanilist/tests/test_sync.py
Testing started at 11:54 PM ...
Launching pytest with arguments C:/Users/ryry0/Documents/Python/anime_staff_checker/pythonanilist/tests/test_sync.py --no-header --no-summary -q in C:\Users\ryry0\Documents\Python\anime_staff_checker\pythonanilist\tests

============================= test session starts =============================
collecting ... collected 16 items

test_sync.py::test_search[Bakemonogatari-anime] 
test_sync.py::test_search[Bakemonogatari-manga] 
test_sync.py::test_search[Senjougahara-character] 
test_sync.py::test_search[Chiwa Saitou-staff] 
test_sync.py::test_search[travis-user] 
test_sync.py::test_get[5081-anime] 
test_sync.py::test_get[101311-manga] 
test_sync.py::test_get[22037-character] 
test_sync.py::test_get[95061-staff] 
test_sync.py::test_get[travis-user] 
test_sync.py::test_get[travis-list_anime] 
test_sync.py::test_get[travis-list_manga] 
test_sync.py::test_get_list_item 
test_sync.py::test_get_activity[travis-anime] 
test_sync.py::test_get_activity[travis-manga] 
test_sync.py::test_get_activity[travis-text] 

============================= 16 passed in 13.78s =============================

Process finished with exit code 0
```
```py
C:\Users\ryry0\AppData\Local\Programs\Python\Python310\python.exe "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pycharm\_jb_pytest_runner.py" --path C:/Users/ryry0/Documents/Python/anime_staff_checker/pythonanilist/tests/test_async.py
Testing started at 11:54 PM ...
Launching pytest with arguments C:/Users/ryry0/Documents/Python/anime_staff_checker/pythonanilist/tests/test_async.py --no-header --no-summary -q in C:\Users\ryry0\Documents\Python\anime_staff_checker\pythonanilist\tests

============================= test session starts =============================
collecting ... collected 16 items

test_async.py::test_search[Bakemonogatari-anime] 
test_async.py::test_search[Bakemonogatari-manga] 
test_async.py::test_search[Senjougahara-character] 
test_async.py::test_search[Chiwa Saitou-staff] 
test_async.py::test_search[travis-user] 
test_async.py::test_get[5081-anime] 
test_async.py::test_get[101311-manga] 
test_async.py::test_get[22037-character] 
test_async.py::test_get[95061-staff] 
test_async.py::test_get[travis-user] 
test_async.py::test_get[travis-list_anime] 
test_async.py::test_get[travis-list_manga] 
test_async.py::test_get_list_item 
test_async.py::test_get_activity[travis-anime] 
test_async.py::test_get_activity[travis-manga] 
test_async.py::test_get_activity[travis-text] 

============================= 16 passed in 12.91s =============================

Process finished with exit code 0
```

Overall, I reduced:

- `sync_client.py`: 1,370 lines → 390 lines
- `async_client.py`: 1,463 lines → 407 lines
- `client_process.py` (NEW): 0 lines → 703 lines
 
Tell me if you have any questions.

### CODE REVIEW

**Comment by AndrielFR** [comment]
not going to lie, i'm out of time to review this pull request, so i haven't replied yet.

**Comment by r-hensley** [comment]
That's totally fine, I made a pull request to an old repo, I'm using my own fork for my purposes so the pull request is really just more for other people to see the existence of my fork/branch. You can do the actual merge at your own pace.

**Comment by AndrielFR** [comment]
> That's totally fine, I made a huge pull request (large rewrite) to an old repo. I'm using my own fork for my purposes so I don't personally need the pull request merger for anything, it's really just more for other people to see the existence of my fork/branch. You can do the actual merge at your own pace.

i understand, great, i'm glad for that

**Review by AndrielFR — APPROVED** [review]
a bit old, but not forgotten, thank you for your PR, i appreciate it

**Pull request merged**
